Проектная работа sprint1 step2
jumpleGo/react-burger pull request #1
Opened 2023-05-08 19:00 UTC by jumpleGo

2023-05-09 07:36 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Проект соответствует макету
- Хорошая работа с `propTypes`
- Хорошая декомпозиция компонентов

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Модалка должна закрываться по нажатию на подложку
- Добавьте проверку ответа сервера - res.ok
- Все файлы компонентов должны находиться в своей отдельной директории
- Похоже, что вы сбили кодировку в github. Если вы меняли её в IDE и в github необходимо вернуть её к изначальному состоянию.

<img width="1108" alt="Снимок экрана 2023-05-09 в 10 31 39" src="https://user-images.githubusercontent.com/60173362/237026009-3a4e2e67-0f15-4b3d-99cc-ab02c0733059.png">

- в описании propTypes компонентов нужно указывать `.isRequired` у пропсов, без этого не контролируется, что пропс передается. После функций shape и arrayOf так же необходимо ставить `isRequired`
Проверьте во всем проекте

- в `BurgerIngredientItemPropsType` у полей необходимо так же ставить `isRequired`
- Между булками должна быть начинка, а не те же булки
- убрать синюю обводку у блоков, эта обводка на макете нужна только что бы сделать опаисание поясняющее к этому блоку

Более подробно описание проблемы смотрите комментарии в pull request.

**Можно лучше**
- Добавьте возможность закрытие нажатием по ESC

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-09 07:36 UTC, andryxxa93 commented on src/components/App/App.jsx
> +        .then(res => res.json())
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-05-09 07:36 UTC, andryxxa93 commented on src/components/App/App.jsx
> +    fetch(URL)
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-05-10 05:49 UTC, andryxxa93 commented
Супер, большая часть проблем исправлена, но осталось ещё несколько:
**Необходимо исправить**
- Похоже, что вы сбили кодировку в github. Если вы меняли её в IDE и в github необходимо вернуть её к изначальному состоянию.
- Все файлы компонентов должны находиться в своей отдельной директории
- В консоли возникает ворнинг связанный с key. У вас `BurgerIngredients` при рендере табов не высталвен `key`  

<img width="545" alt="Снимок экрана 2023-05-10 в 08 47 04" src="https://github.com/jumpleGo/react-burger/assets/60173362/beb2ad32-38cf-4943-9d18-e4e727e83687">

2023-05-12 06:51 UTC, jumpleGo commented
Я исправил все недостатки кроме одного, артефакты ^M. Потратил 2 дня на поиск проблемы но пока ничего не нашел. Обычно я работаю с битбакетом и там все нормально. В IDE я поменял переход на новую строку под формат GitHub но он не дает перезаписать отступы так как не видит разницы. В следующих коммитах это должно исправиться, т.к. я буду работать в файлах и переходы на новую строку изменятся

2023-05-12 20:22 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-15 20:59 UTC, merged